apiVersion: v1
kind: Service
metadata:
  name: front-end-np
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

# Resumidamente, este arquivo YAML cria um serviço chamado "front-end-np" do tipo NodePort, expondo a aplicação externamente
# através de um número de porta fixo (30001) em cada nó do cluster. Este tipo de serviço é útil quando você precisa acessar
# sua aplicação de fora do cluster, mas ainda está em um ambiente de desenvolvimento ou teste.