apiVersion: v1
kind: Namespace
metadata:
  name: develop

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-front
  namespace: develop
  labels: 
    app: develop
spec:
  selector:
    matchLabels:
      app: develop
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: develop
    spec:
      containers:
        - name: dev-front-pod
          image: denirow/prog-redes
          ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  namespace: develop
  name: cip-develop
spec:
  type: ClusterIP
  selector:
    app: develop
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-develop
  namespace: develop
spec:
  ingressClassName: nginx
  rules:
  - host: develop.10.49.10.63.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cip-develop
            port:
              number: 80