apiVersion: v1
kind: Namespace
metadata:
  name: develop

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-develop
  namespace: develop
  labels: 
    app: label-develop
spec:
  selector:
    matchLabels:
      app: label-develop
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: label-develop
    spec:
      containers:
        - name: front-develop
          image: valfranc/web-nlw-develop:latest
          ports:
          - containerPort: 80
          env:
          - name: VITE_API_URL
            value: "http://api-develop.192.168.56.1.nip.io"
          command: ["/bin/sh", "-c", "git pull && npm i && npm run dev -- --host --port 80"]
        - name: back-develop
          image: valfranc/server-nlw-develop:latest
          ports:
          - containerPort: 3333
          env:  # Correção: env deve estar dentro de containers
          - name: DATABASE_URL
            value: "mongodb+srv://valmirfrancisco1:alBYIjPGChRt0tu4@cluster0.mcejfas.mongodb.net/develop"
          command: ["/bin/sh", "-c", "git pull && npm i && npx prisma db push && npx prisma db seed && npm run dev"]

---

apiVersion: v1
kind: Service
metadata:
  namespace: develop
  name: cip-develop
spec:
  type: ClusterIP
  selector:
    app: label-develop
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: api
    port: 3333
    targetPort: 3333

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-develop
  namespace: develop
spec:
  ingressClassName: nginx
  rules:
  - host: develop.192.168.56.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cip-develop
            port:
              number: 80
  - host: api-develop.192.168.56.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cip-develop
            port:
              number: 3333