apiVersion: v1
kind: Namespace
metadata:
  name: homolog

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-homolog
  namespace: homolog
  labels: 
    app: label-homolog
spec:
  selector:
    matchLabels:
      app: label-homolog
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: label-homolog
    spec:
      containers:
        - name: front-homolog
          image: valfranc/web-nlw-homolog:latest
          ports:
          - containerPort: 80
          env:
          - name: VITE_API_URL
            value: "http://api-homolog.192.168.56.1.nip.io"
          command: ["/bin/sh", "-c", "git pull && npm i && npm run dev -- --host --port 80"]
        - name: back-homolog
          image: valfranc/server-nlw-homolog:latest
          ports:
          - containerPort: 3333
          env:  # Correção: env deve estar dentro de containers
          - name: DATABASE_URL
            value: "mongodb+srv://valmirfrancisco1:alBYIjPGChRt0tu4@cluster0.mcejfas.mongodb.net/homolog"
          command: ["/bin/sh", "-c", "git pull && npm i && npx prisma db push && npx prisma db seed && npm run dev"]
      

---

apiVersion: v1
kind: Service
metadata:
  namespace: homolog
  name: cip-homolog
spec:
  type: ClusterIP
  selector:
    app: label-homolog
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: api
    port: 3333
    targetPort: 3333

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-homolog
  namespace: homolog
spec:
  ingressClassName: nginx
  rules:
  - host: homolog.192.168.56.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cip-homolog
            port:
              number: 80
  - host: api-homolog.192.168.56.1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cip-homolog
            port:
              number: 3333